"""add_booking_code_and_country_fields

Revision ID: 12794784c116
Revises: 3a3f936e87c4
Create Date: 2026-04-04 10:05:43.416268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12794784c116'
down_revision: Union[str, Sequence[str], None] = '3a3f936e87c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('rate_plan_code', sa.String(length=2000), nullable=True))
    op.add_column('bookings', sa.Column('booking_code', sa.String(length=4000), nullable=True))
    op.add_column('bookings', sa.Column('booking_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('country_of_residence', sa.String(length=2), nullable=True))
    op.add_column('bookings', sa.Column('external_booking_reference', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'external_booking_reference')
    op.drop_column('bookings', 'country_of_residence')
    op.drop_column('bookings', 'booking_code_expires_at')
    op.drop_column('bookings', 'booking_code')
    op.drop_column('bookings', 'rate_plan_code')
    # ### end Alembic commands ###
