"""add_static_data_cache_tables

Revision ID: 3a3f936e87c4
Revises: 6be8710c5d03
Create Date: 2026-04-04 09:07:09.594476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a3f936e87c4'
down_revision: Union[str, Sequence[str], None] = '6be8710c5d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_types',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('countries',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('currencies',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('hotel_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jp_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('zone_jpdcode', sa.String(length=20), nullable=True),
    sa.Column('category_type', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('city_name', sa.String(length=255), nullable=True),
    sa.Column('city_jpdcode', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_cache_jp_code'), 'hotel_cache', ['jp_code'], unique=True)
    op.create_index(op.f('ix_hotel_cache_zone_jpdcode'), 'hotel_cache', ['zone_jpdcode'], unique=False)
    op.create_table('hotel_categories',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('hotel_content_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jp_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('descriptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('check_in_time', sa.String(length=10), nullable=True),
    sa.Column('check_out_time', sa.String(length=10), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_content_cache_jp_code'), 'hotel_content_cache', ['jp_code'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jpdcode', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('area_type', sa.String(length=10), nullable=True),
    sa.Column('searchable', sa.Boolean(), nullable=False),
    sa.Column('parent_jpdcode', sa.String(length=20), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_code'), 'zones', ['code'], unique=False)
    op.create_index(op.f('ix_zones_jpdcode'), 'zones', ['jpdcode'], unique=True)
    op.create_index(op.f('ix_zones_parent_jpdcode'), 'zones', ['parent_jpdcode'], unique=False)
    op.drop_constraint(op.f('bookings_idempotency_key_key'), 'bookings', type_='unique')
    op.drop_index(op.f('idx_bookings_idempotency_key'), table_name='bookings')
    op.drop_index(op.f('idx_bookings_user_id'), table_name='bookings')
    op.create_index(op.f('ix_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('idx_users_external_id'), table_name='users')
    op.drop_constraint(op.f('users_external_id_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.alter_column('webhook_subscriptions', 'events',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('webhook_subscriptions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('webhook_subscriptions', 'failure_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_subscriptions', 'failure_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('webhook_subscriptions', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('webhook_subscriptions', 'events',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.create_unique_constraint(op.f('users_external_id_key'), 'users', ['external_id'])
    op.create_index(op.f('idx_users_external_id'), 'users', ['external_id'], unique=False)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_idempotency_key'), table_name='bookings')
    op.create_index(op.f('idx_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('idx_bookings_idempotency_key'), 'bookings', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('bookings_idempotency_key_key'), 'bookings', ['idempotency_key'])
    op.drop_index(op.f('ix_zones_parent_jpdcode'), table_name='zones')
    op.drop_index(op.f('ix_zones_jpdcode'), table_name='zones')
    op.drop_index(op.f('ix_zones_code'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_hotel_content_cache_jp_code'), table_name='hotel_content_cache')
    op.drop_table('hotel_content_cache')
    op.drop_table('hotel_categories')
    op.drop_index(op.f('ix_hotel_cache_zone_jpdcode'), table_name='hotel_cache')
    op.drop_index(op.f('ix_hotel_cache_jp_code'), table_name='hotel_cache')
    op.drop_table('hotel_cache')
    op.drop_table('currencies')
    op.drop_table('countries')
    op.drop_table('board_types')
    # ### end Alembic commands ###
